import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtemp, readFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import { hashPassword } from '../server/auth.mjs';
import { datasetCSV } from '../src/csv.js';
import { defaults } from '../src/domain.js';
test('HTTP operator flow enforces auth, origin, CSRF, revision and private exports', async t => {
  const listener=net.createServer(); await new Promise(resolve=>listener.listen(0,'127.0.0.1',resolve));
  const port=listener.address().port; await new Promise(resolve=>listener.close(resolve));
  const origin=`http://127.0.0.1:${port}`, password='integration-only-password';
  const dir=await mkdtemp(path.join(os.tmpdir(),'stockwise-http-'));
  const child=spawn(process.execPath,['scripts/server.mjs'],{cwd:new URL('../',import.meta.url),env:{...process.env,NODE_ENV:'test',PORT:String(port),APP_ORIGIN:origin,DATA_DIR:dir,OPERATOR_PASSWORD_HASH:hashPassword(password)},stdio:['ignore','pipe','pipe']});
  t.after(()=>child.kill('SIGTERM'));
  await new Promise((resolve,reject)=>{child.stdout.on('data',chunk=>{if(chunk.toString().includes('Stockwise ready'))resolve()});child.on('error',reject);child.on('exit',code=>reject(new Error('Server exited '+code)));});
  const get=async url=>fetch(origin+url);
  assert.equal((await get('/health')).status,200);
  for (const [asset,type] of [['/favicon.ico','image/x-icon'],['/public/brand/favicon-v2.png','image/png'],['/public/brand/favicon.ico','image/x-icon']]) {
    const icon=await get(asset);
    assert.equal(icon.status,200);
    assert.equal(icon.headers.get('content-type'),type);
    assert.ok((await icon.arrayBuffer()).byteLength>0);
  }
  assert.equal((await get('/api/workspace')).status,401);
  assert.equal((await get('/server/auth.mjs')).status,404);
  const html=await get('/'); assert.ok(html.headers.get('content-security-policy').includes("frame-ancestors 'none'"));
  const post=async (url,value,headers={})=>fetch(origin+url,{method:'POST',headers:{'Content-Type':'application/json',Origin:origin,...headers},body:JSON.stringify(value)});
  assert.equal((await post('/api/login',{password},{Origin:'https://evil.example'})).status,403);
  assert.equal((await post('/api/login',{password:'wrong'})).status,401);
  const login=await post('/api/login',{password}); assert.equal(login.status,200);
  const cookie=login.headers.get('set-cookie').split(';')[0]; assert.ok(login.headers.get('set-cookie').includes('HttpOnly'));
  const {csrf}=await login.json();
  const authGet=async url=>fetch(origin+url,{headers:{Cookie:cookie}});
  assert.equal((await authGet('/api/session')).status,200);
  const data=JSON.parse(await readFile(new URL('../public/data/retail.json',import.meta.url)));
  const workspace={csv:datasetCSV(data.products,false),scenario:defaults,currency:'GBP',source:'real',selected:data.products[0].sku,revision:0};
  const put=async(value,token=csrf)=>fetch(origin+'/api/workspace',{method:'PUT',headers:{'Content-Type':'application/json',Origin:origin,Cookie:cookie,'X-CSRF-Token':token},body:JSON.stringify(value)});
  assert.equal((await put(workspace,'bad')).status,403);
  assert.equal((await put({...workspace,currency:'FAKE'})).status,400);
  assert.equal((await put(workspace)).status,200);
  assert.equal((await put(workspace)).status,409);
  const restored=await(await authGet('/api/workspace')).json(); assert.equal(restored.workspace.revision,1);
  const exported=await authGet('/api/plan.csv'); assert.equal(exported.status,200); assert.ok(exported.headers.get('content-disposition').includes('.csv')); assert.ok((await exported.text()).includes('GBP'));
  assert.equal((await post('/api/logout',{}, {Cookie:cookie,'X-CSRF-Token':csrf})).status,200);
  assert.equal((await authGet('/api/workspace')).status,401);
});
